import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { NodeProps } from "../repositories/nodeRepository.js";
import type { OntologySnapshot } from "./ontologySnapshot.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.resolve(__dirname, "../../../../neo4j/migrations");

function cypherLiteral(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    // Neo4j property arrays must be homogeneous primitives; a nested-object
    // array (e.g. Entity.properties) is stored as a JSON string, same as
    // the repository layer, so restore round-trips it identically.
    if (value.some((v) => typeof v === "object" && v !== null)) {
      return cypherLiteral(JSON.stringify(value));
    }
    return `[${value.map(cypherLiteral).join(", ")}]`;
  }
  const escaped = String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  return `'${escaped}'`;
}

function mergeNodeStatement(label: string, props: NodeProps): string {
  const { id, ...rest } = props;
  const assignments = Object.entries(rest)
    .map(([key, value]) => `n.${key} = ${cypherLiteral(value)}`)
    .join(", ");
  return `MERGE (n:${label} {id: ${cypherLiteral(id)}}) SET ${assignments || "n = n"};`;
}

async function loadMigrations(): Promise<string> {
  try {
    const files = (await readdir(MIGRATIONS_DIR)).filter((f) => f.endsWith(".cypher")).sort();
    const contents = await Promise.all(
      files.map((f) => readFile(path.join(MIGRATIONS_DIR, f), "utf-8"))
    );
    return contents.join("\n");
  } catch {
    return "";
  }
}

/**
 * Emits a deterministic, idempotent Cypher script that reconstructs the
 * ontology from scratch on any Neo4j instance (spec section 37). Not used
 * by this app's own restore path (which reads ontology.json through the
 * driver with parameters) — it's the portable, human/cypher-shell-runnable
 * artifact for transferring the ontology outside this tool.
 */
export async function generateCypherExport(snapshot: OntologySnapshot): Promise<string> {
  const lines: string[] = [
    "// Generated by Ontology Builder — reconstructs the ontology from scratch.",
    `// Generated at ${snapshot.metadata.createdAt}`,
    "",
    "// --- constraints & indexes ---",
    await loadMigrations(),
    "",
    "// --- nodes ---"
  ];

  const nodeCollections: Array<[string, NodeProps[]]> = [
    ["Entity", snapshot.entities],
    ["Concept", snapshot.concepts],
    ["RelationshipDefinition", snapshot.relationships],
    ["Rule", snapshot.rules],
    ["State", snapshot.states],
    ["Capability", snapshot.capabilities],
    ["Agent", snapshot.agents],
    ["Policy", snapshot.policies],
    ["Issue", snapshot.issues],
    ["Handoff", snapshot.handoffs],
    ["Decision", snapshot.decisions],
    ["Execution", snapshot.executions],
    ["LearningEvent", snapshot.learningEvents],
    ["OntologyVersion", snapshot.versions]
  ];

  for (const [label, items] of nodeCollections) {
    for (const item of items) {
      lines.push(mergeNodeStatement(label, item));
    }
  }

  lines.push("", "// --- relationship edges ---");
  for (const rel of snapshot.relationships) {
    lines.push(
      `MATCH (a:${rel.sourceLabel} {id: ${cypherLiteral(rel.sourceId)}}), (b:${rel.targetLabel} {id: ${cypherLiteral(rel.targetId)}}) ` +
        `MERGE (a)-[r:${rel.type} {relationshipDefinitionId: ${cypherLiteral(rel.id)}}]->(b) SET r.cardinality = ${cypherLiteral(rel.cardinality)};`
    );
  }

  lines.push("", "// --- handoff edges ---");
  for (const handoff of snapshot.handoffs) {
    lines.push(
      `MATCH (h:Handoff {id: ${cypherLiteral(handoff.id)}}), (from:Agent {id: ${cypherLiteral(handoff.fromAgentId)}}), (to:Agent {id: ${cypherLiteral(handoff.toAgentId)}}) ` +
        `MERGE (h)-[:FROM_AGENT]->(from) MERGE (h)-[:TO_AGENT]->(to);`
    );
  }

  lines.push("", "// --- version membership (CONTAINS) ---");
  for (const entry of snapshot.versionContents) {
    lines.push(
      `MATCH (v:OntologyVersion {id: ${cypherLiteral(entry.versionId)}}), (el:${entry.label} {id: ${cypherLiteral(entry.elementId)}}) ` +
        `MERGE (v)-[:CONTAINS]->(el);`
    );
  }

  return lines.join("\n") + "\n";
}
