import { existsSync } from "node:fs";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { KNOWN_COLUMNS, splitColumns, type NodeProps } from "../repositories/nodeRepository.js";
import type { OntologySnapshot } from "./ontologySnapshot.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
function resolveMigrationsDir(): string {
  const candidates = [
    path.resolve(process.cwd(), "postgres/migrations"),
    path.resolve(__dirname, "../../../postgres/migrations"),
    path.resolve(__dirname, "../../../../postgres/migrations")
  ];
  return candidates.find((dir) => existsSync(dir)) ?? candidates[0]!;
}
const MIGRATIONS_DIR = resolveMigrationsDir();

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const escaped = String(value).replace(/'/g, "''");
  return `'${escaped}'`;
}

function jsonLiteral(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function insertNodeStatement(label: string, props: NodeProps): string {
  const { id, ...rest } = props;
  const { known, rest: data } = splitColumns(rest);
  delete data.createdAt;
  delete data.updatedAt;
  const columns = ["id", "label", ...KNOWN_COLUMNS, "data"];
  const values = [
    sqlLiteral(id),
    sqlLiteral(label),
    ...KNOWN_COLUMNS.map((col) => sqlLiteral(known[col] ?? null)),
    jsonLiteral(data)
  ];
  const updateAssignments = [...KNOWN_COLUMNS, "data"]
    .map((col) => `${col} = EXCLUDED.${col}`)
    .join(", ");
  return (
    `INSERT INTO ontology_nodes (${columns.join(", ")}) VALUES (${values.join(", ")}) ` +
    `ON CONFLICT (id) DO UPDATE SET ${updateAssignments}, updated_at = now();`
  );
}

async function loadMigrations(): Promise<string> {
  try {
    const files = (await readdir(MIGRATIONS_DIR)).filter((f) => f.endsWith(".sql")).sort();
    const contents = await Promise.all(
      files.map((f) => readFile(path.join(MIGRATIONS_DIR, f), "utf-8"))
    );
    return contents.join("\n");
  } catch {
    return "";
  }
}

/**
 * Emits a deterministic, idempotent SQL script that reconstructs the
 * ontology from scratch on any PostgreSQL instance (spec section 37). Not
 * used by this app's own restore path (which reads ontology.json through
 * `pg` with parameters) — it's the portable, human/psql-runnable artifact
 * for transferring the ontology outside this tool.
 */
export async function generateSqlExport(snapshot: OntologySnapshot): Promise<string> {
  const lines: string[] = [
    "-- Generated by Ontology Builder — reconstructs the ontology from scratch.",
    `-- Generated at ${snapshot.metadata.createdAt}`,
    "",
    "-- --- tables & indexes ---",
    await loadMigrations(),
    "",
    "-- --- nodes ---"
  ];

  const nodeCollections: Array<[string, NodeProps[]]> = [
    ["Entity", snapshot.entities],
    ["Concept", snapshot.concepts],
    ["RelationshipDefinition", snapshot.relationships],
    ["Rule", snapshot.rules],
    ["State", snapshot.states],
    ["Capability", snapshot.capabilities],
    ["Agent", snapshot.agents],
    ["Policy", snapshot.policies],
    ["Issue", snapshot.issues],
    ["Handoff", snapshot.handoffs],
    ["Decision", snapshot.decisions],
    ["Execution", snapshot.executions],
    ["LearningEvent", snapshot.learningEvents]
  ];

  for (const [label, items] of nodeCollections) {
    for (const item of items) {
      lines.push(insertNodeStatement(label, item));
    }
  }

  lines.push("", "-- --- ontology versions ---");
  for (const version of snapshot.versions) {
    lines.push(
      `INSERT INTO ontology_versions (id, version, description, created_by, status, created_at) ` +
        `VALUES (${sqlLiteral(version.id)}, ${sqlLiteral(version.version)}, ${sqlLiteral(version.description)}, ` +
        `${sqlLiteral(version.createdBy)}, ${sqlLiteral(version.status)}, ${sqlLiteral(version.createdAt)}) ` +
        `ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, description = EXCLUDED.description, ` +
        `created_by = EXCLUDED.created_by, status = EXCLUDED.status;`
    );
  }

  lines.push("", "-- --- relationship edges ---");
  for (const rel of snapshot.relationships) {
    lines.push(
      `INSERT INTO ontology_edges (id, source_id, target_id, type, relationship_definition_id, cardinality) ` +
        `VALUES (${sqlLiteral(randomUUID())}, ${sqlLiteral(rel.sourceId)}, ${sqlLiteral(rel.targetId)}, ` +
        `${sqlLiteral(rel.type)}, ${sqlLiteral(rel.id)}, ${sqlLiteral(rel.cardinality)}) ` +
        `ON CONFLICT (relationship_definition_id) WHERE relationship_definition_id IS NOT NULL ` +
        `DO UPDATE SET cardinality = EXCLUDED.cardinality;`
    );
  }

  lines.push("", "-- --- handoff edges ---");
  for (const handoff of snapshot.handoffs) {
    for (const [type, targetId] of [
      ["FROM_AGENT", handoff.fromAgentId],
      ["TO_AGENT", handoff.toAgentId]
    ] as const) {
      lines.push(
        `INSERT INTO ontology_edges (id, source_id, target_id, type) ` +
          `VALUES (${sqlLiteral(randomUUID())}, ${sqlLiteral(handoff.id)}, ${sqlLiteral(targetId)}, ${sqlLiteral(type)}) ` +
          `ON CONFLICT (source_id, target_id, type) WHERE relationship_definition_id IS NULL DO NOTHING;`
      );
    }
  }

  lines.push("", "-- --- version membership ---");
  for (const entry of snapshot.versionContents) {
    lines.push(
      `INSERT INTO version_contents (version_id, node_id) ` +
        `VALUES (${sqlLiteral(entry.versionId)}, ${sqlLiteral(entry.elementId)}) ` +
        `ON CONFLICT (version_id, node_id) DO NOTHING;`
    );
  }

  return lines.join("\n") + "\n";
}
